/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:00:12 GMT 2018
 */

package org.telegram.telegrambots.meta.api.methods.updatingmessages;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.methods.updatingmessages.EditMessageCaption;
import org.telegram.telegrambots.meta.api.objects.replykeyboard.InlineKeyboardMarkup;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EditMessageCaption_ESTest extends EditMessageCaption_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setParseMode("06w>xA+A<QIvZ!*Q/B");
      String string0 = editMessageCaption1.getParseMode();
      assertEquals("06w>xA+A<QIvZ!*Q/B", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setParseMode("");
      String string0 = editMessageCaption1.getParseMode();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      Integer integer0 = new Integer(20);
      editMessageCaption0.setMessageId(integer0);
      Integer integer1 = editMessageCaption0.getMessageId();
      assertEquals(20, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      Integer integer0 = new Integer(0);
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setMessageId(integer0);
      Integer integer1 = editMessageCaption1.getMessageId();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      Integer integer0 = new Integer((-1));
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setMessageId(integer0);
      Integer integer1 = editMessageCaption1.getMessageId();
      assertEquals((-1), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setInlineMessageId(", caption='");
      String string0 = editMessageCaption1.getInlineMessageId();
      assertEquals(", caption='", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      editMessageCaption0.setInlineMessageId("");
      String string0 = editMessageCaption0.getInlineMessageId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setChatId("editmessagecaption");
      String string0 = editMessageCaption1.getChatId();
      assertEquals("editmessagecaption", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setChatId("");
      String string0 = editMessageCaption1.getChatId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setCaption(",}XRmKi");
      String string0 = editMessageCaption1.getCaption();
      assertEquals(",}XRmKi", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      editMessageCaption0.setCaption("");
      String string0 = editMessageCaption0.getCaption();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      // Undeclared exception!
      try { 
        editMessageCaption0.deserializeResponse("null array");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.updatingmessages.EditMessageCaption", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setChatId("editmessagecaption");
      InlineKeyboardMarkup inlineKeyboardMarkup0 = new InlineKeyboardMarkup();
      editMessageCaption0.setReplyMarkup(inlineKeyboardMarkup0);
      Integer integer0 = new Integer((-3810));
      editMessageCaption0.setMessageId(integer0);
      editMessageCaption1.validate();
      assertSame(editMessageCaption0, editMessageCaption1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      Integer integer0 = new Integer(101);
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setMessageId(integer0);
      editMessageCaption1.setInlineMessageId(" YErK!}\";-");
      try { 
        editMessageCaption1.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // MessageId parameter must be empty if inlineMessageId is provided
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.updatingmessages.EditMessageCaption", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setChatId("editmessagecaption");
      editMessageCaption1.setInlineMessageId("editmessagecaption");
      try { 
        editMessageCaption0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // ChatId parameter must be empty if inlineMessageId is provided
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.updatingmessages.EditMessageCaption", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setChatId("editmessagecaption");
      Integer integer0 = new Integer((-3810));
      editMessageCaption0.setMessageId(integer0);
      editMessageCaption1.validate();
      assertNull(editMessageCaption1.getCaption());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      try { 
        editMessageCaption0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // ChatId parameter can't be empty if inlineMessageId is not present
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.updatingmessages.EditMessageCaption", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      String string0 = editMessageCaption0.toString();
      assertEquals("EditMessageCaption{chatId='null', messageId=null, inlineMessageId='null', caption='null', replyMarkup=null, parseMode='null'}", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      String string0 = editMessageCaption0.getMethod();
      assertEquals("editmessagecaption", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      String string0 = editMessageCaption0.getInlineMessageId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      String string0 = editMessageCaption0.getCaption();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      editMessageCaption0.setInlineMessageId("");
      editMessageCaption0.validate();
      assertEquals("", editMessageCaption0.getInlineMessageId());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      EditMessageCaption editMessageCaption1 = editMessageCaption0.setChatId("editmessagecaption");
      try { 
        editMessageCaption1.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // MessageId parameter can't be empty if inlineMessageId is not present
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.updatingmessages.EditMessageCaption", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      Integer integer0 = editMessageCaption0.getMessageId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      InlineKeyboardMarkup inlineKeyboardMarkup0 = new InlineKeyboardMarkup();
      editMessageCaption0.setReplyMarkup(inlineKeyboardMarkup0);
      InlineKeyboardMarkup inlineKeyboardMarkup1 = editMessageCaption0.getReplyMarkup();
      assertSame(inlineKeyboardMarkup1, inlineKeyboardMarkup0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      String string0 = editMessageCaption0.getParseMode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      String string0 = editMessageCaption0.getChatId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      InlineKeyboardMarkup inlineKeyboardMarkup0 = editMessageCaption0.getReplyMarkup();
      assertNull(inlineKeyboardMarkup0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      EditMessageCaption editMessageCaption0 = new EditMessageCaption();
      try { 
        editMessageCaption0.deserializeResponse("editmessagecaption");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Unable to deserialize response
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.updatingmessages.EditMessageCaption", e);
      }
  }
}
