/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:41:32 GMT 2018
 */

package org.telegram.telegrambots.meta.api.methods;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.methods.GetFile;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GetFile_ESTest extends GetFile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetFile getFile0 = new GetFile();
      // Undeclared exception!
      try { 
        getFile0.deserializeResponse("null");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.GetFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GetFile getFile0 = new GetFile();
      GetFile getFile1 = getFile0.setFileId("#NS.z4&+ elEOL");
      String string0 = getFile1.getFileId();
      assertEquals("#NS.z4&+ elEOL", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GetFile getFile0 = new GetFile();
      GetFile getFile1 = getFile0.setFileId("");
      String string0 = getFile1.getFileId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GetFile getFile0 = new GetFile();
      try { 
        getFile0.deserializeResponse("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Unable to deserialize response
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.GetFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GetFile getFile0 = new GetFile();
      try { 
        getFile0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // FileId can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.GetFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      GetFile getFile0 = new GetFile();
      getFile0.setFileId("getFile");
      getFile0.validate();
      assertEquals("getFile", getFile0.getFileId());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      GetFile getFile0 = new GetFile();
      String string0 = getFile0.getMethod();
      assertEquals("getFile", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      GetFile getFile0 = new GetFile();
      String string0 = getFile0.getFileId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      GetFile getFile0 = new GetFile();
      String string0 = getFile0.toString();
      assertEquals("GetFile{fileId='null'}", string0);
  }
}
