/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 15:03:05 GMT 2018
 */

package org.telegram.telegrambots.starter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import java.util.Optional;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.TelegramBotsApi;
import org.telegram.telegrambots.meta.generics.LongPollingBot;
import org.telegram.telegrambots.meta.generics.WebhookBot;
import org.telegram.telegrambots.starter.TelegramBotStarterConfiguration;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TelegramBotStarterConfiguration_ESTest extends TelegramBotStarterConfiguration_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TelegramBotStarterConfiguration telegramBotStarterConfiguration0 = new TelegramBotStarterConfiguration();
      TelegramBotsApi telegramBotsApi0 = telegramBotStarterConfiguration0.telegramBotsApi();
      assertNotNull(telegramBotsApi0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TelegramBotStarterConfiguration telegramBotStarterConfiguration0 = new TelegramBotStarterConfiguration();
      TelegramBotsApi telegramBotsApi0 = new TelegramBotsApi();
      LinkedList<WebhookBot> linkedList0 = new LinkedList<WebhookBot>();
      Optional<List<WebhookBot>> optional0 = Optional.ofNullable((List<WebhookBot>) linkedList0);
      // Undeclared exception!
      try { 
        telegramBotStarterConfiguration0.telegramBotInitializer(telegramBotsApi0, (Optional<List<LongPollingBot>>) null, optional0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.starter.TelegramBotStarterConfiguration", e);
      }
  }
}
