/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:45:03 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects.payments;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.PhotoSize;
import org.telegram.telegrambots.meta.api.objects.payments.Invoice;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Invoice_ESTest extends Invoice_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Invoice invoice0 = new Invoice();
      String string0 = invoice0.getStartParameter();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Invoice invoice0 = new Invoice();
      String string0 = invoice0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Invoice invoice0 = new Invoice();
      String string0 = invoice0.getCurrency();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Invoice invoice0 = new Invoice();
      PhotoSize photoSize0 = invoice0.getPhoto();
      assertNull(photoSize0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Invoice invoice0 = new Invoice();
      String string0 = invoice0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Invoice invoice0 = new Invoice();
      Integer integer0 = invoice0.getTotalAmount();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Invoice invoice0 = new Invoice();
      String string0 = invoice0.toString();
      assertEquals("Invoice{title='null', description='null', startParameter='null', currency='null', totalAmount=null, photo=null}", string0);
  }
}
