/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:43:45 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects.payments;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.payments.OrderInfo;
import org.telegram.telegrambots.meta.api.objects.payments.ShippingAddress;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OrderInfo_ESTest extends OrderInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();
      String string0 = orderInfo0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();
      String string0 = orderInfo0.getPhoneNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();
      String string0 = orderInfo0.toString();
      assertEquals("OrderInfo{name='null', phoneNumber='null', email='null', shippingAddress=null}", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();
      String string0 = orderInfo0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();
      ShippingAddress shippingAddress0 = orderInfo0.getShippingAddress();
      assertNull(shippingAddress0);
  }
}
