/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:45:02 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects.payments;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.User;
import org.telegram.telegrambots.meta.api.objects.payments.OrderInfo;
import org.telegram.telegrambots.meta.api.objects.payments.PreCheckoutQuery;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PreCheckoutQuery_ESTest extends PreCheckoutQuery_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PreCheckoutQuery preCheckoutQuery0 = new PreCheckoutQuery();
      String string0 = preCheckoutQuery0.getInvoicePayload();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PreCheckoutQuery preCheckoutQuery0 = new PreCheckoutQuery();
      String string0 = preCheckoutQuery0.getShippingOptionId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PreCheckoutQuery preCheckoutQuery0 = new PreCheckoutQuery();
      Integer integer0 = preCheckoutQuery0.getTotalAmount();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PreCheckoutQuery preCheckoutQuery0 = new PreCheckoutQuery();
      String string0 = preCheckoutQuery0.toString();
      assertEquals("PreCheckoutQuery{id='null', from=null, currency='null', totalAmount=null, invoicePayload='null', shippingOptionId='null', orderInfo=null}", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PreCheckoutQuery preCheckoutQuery0 = new PreCheckoutQuery();
      String string0 = preCheckoutQuery0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PreCheckoutQuery preCheckoutQuery0 = new PreCheckoutQuery();
      User user0 = preCheckoutQuery0.getFrom();
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PreCheckoutQuery preCheckoutQuery0 = new PreCheckoutQuery();
      OrderInfo orderInfo0 = preCheckoutQuery0.getOrderInfo();
      assertNull(orderInfo0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PreCheckoutQuery preCheckoutQuery0 = new PreCheckoutQuery();
      String string0 = preCheckoutQuery0.getCurrency();
      assertNull(string0);
  }
}
