/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 05 15:02:25 GMT 2018
 */

package org.telegram.telegrambots.extensions.bots.commandbot.commands.helpCommand;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.extensions.bots.commandbot.commands.helpCommand.HelpCommand;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ManCommand_ESTest extends ManCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HelpCommand helpCommand0 = new HelpCommand("s+", (String) null, (String) null);
      String string0 = helpCommand0.getExtendedDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HelpCommand helpCommand0 = new HelpCommand(", orderInfo=", ", orderInfo=", "");
      String string0 = helpCommand0.getExtendedDescription();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HelpCommand helpCommand0 = new HelpCommand("-----------------", "-----------------", "-----------------");
      String string0 = helpCommand0.getExtendedDescription();
      assertEquals("-----------------", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HelpCommand helpCommand0 = new HelpCommand();
      String string0 = helpCommand0.toMan();
      assertEquals("<b>/help</b>\nshows all commands. Use /help [command] for more info\n-----------------\nThis command displays all commands the bot has to offer.\n /help [command] can display deeper information", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HelpCommand helpCommand0 = new HelpCommand("t/Upoyl5:ObP", ")2E(TEjfa0RiHou", (String) null);
      String string0 = helpCommand0.toMan();
      assertEquals("<b>/t/upoyl5:obp</b>\n)2E(TEjfa0RiHou\n-----------------\n", string0);
  }
}
