/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:20:05 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects.inlinequery.inputmessagecontent;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.inlinequery.inputmessagecontent.InputVenueMessageContent;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InputVenueMessageContent_ESTest extends InputVenueMessageContent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      inputVenueMessageContent0.setTitle("InputVenueMessageContent{latitude=null, longitude=null, title='null', address='null', foursquareId='null', foursquareType='null'}");
      String string0 = inputVenueMessageContent0.getTitle();
      assertEquals("InputVenueMessageContent{latitude=null, longitude=null, title='null', address='null', foursquareId='null', foursquareType='null'}", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      inputVenueMessageContent0.setTitle("");
      String string0 = inputVenueMessageContent0.getTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = new Float(0.0F);
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setLongitude(float0);
      Float float1 = inputVenueMessageContent1.getLongitude();
      assertEquals(0.0F, (float)float1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = new Float(349.03976F);
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setLongitude(float0);
      Float float1 = inputVenueMessageContent1.getLongitude();
      assertEquals(349.03976F, (float)float1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = new Float((-1.0));
      inputVenueMessageContent0.setLongitude(float0);
      Float float1 = inputVenueMessageContent0.getLongitude();
      assertEquals((-1.0F), (float)float1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = new Float(2169.51);
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setLatitude(float0);
      Float float1 = inputVenueMessageContent1.getLatitude();
      assertEquals(2169.51F, (float)float1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = new Float((-1.0F));
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setLatitude(float0);
      Float float1 = inputVenueMessageContent1.getLatitude();
      assertEquals((-1.0F), (float)float1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setFoursquareType(")vBX:/M`Oyxj;<");
      String string0 = inputVenueMessageContent1.getFoursquareType();
      assertEquals(")vBX:/M`Oyxj;<", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setFoursquareType("");
      String string0 = inputVenueMessageContent1.getFoursquareType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      inputVenueMessageContent0.setFoursquareId(", foursquareType='");
      String string0 = inputVenueMessageContent0.getFoursquareId();
      assertEquals(", foursquareType='", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setAddress("sAyRRC5)\"$]m20_w]Q");
      String string0 = inputVenueMessageContent1.getAddress();
      assertEquals("sAyRRC5)\"$]m20_w]Q", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setAddress("");
      String string0 = inputVenueMessageContent1.getAddress();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = new Float(359.13968F);
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setLongitude(float0);
      inputVenueMessageContent0.setLatitude(float0);
      inputVenueMessageContent0.setTitle("InputVenueMessageContent{latitude=null, longitude=null, title='null', address='null', foursquareId='null', foursquareType='null'}");
      inputVenueMessageContent1.setAddress("");
      try { 
        inputVenueMessageContent0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Address parameter can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.objects.inlinequery.inputmessagecontent.InputVenueMessageContent", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setTitle("");
      Float float0 = new Float(4086.7788223);
      InputVenueMessageContent inputVenueMessageContent2 = inputVenueMessageContent1.setLongitude(float0);
      InputVenueMessageContent inputVenueMessageContent3 = inputVenueMessageContent2.setLatitude(float0);
      try { 
        inputVenueMessageContent3.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Title parameter can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.objects.inlinequery.inputmessagecontent.InputVenueMessageContent", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = new Float(359.13968F);
      inputVenueMessageContent0.setLongitude(float0);
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setLatitude(float0);
      inputVenueMessageContent0.setTitle("InputVenueMessageContent{latitude=null, longitude=null, title='null', address='null', foursquareId='null', foursquareType='null'}");
      try { 
        inputVenueMessageContent1.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Address parameter can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.objects.inlinequery.inputmessagecontent.InputVenueMessageContent", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = new Float(359.13968F);
      inputVenueMessageContent0.setLongitude(float0);
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setLatitude(float0);
      try { 
        inputVenueMessageContent1.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Title parameter can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.objects.inlinequery.inputmessagecontent.InputVenueMessageContent", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      try { 
        inputVenueMessageContent0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Latitude parameter can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.objects.inlinequery.inputmessagecontent.InputVenueMessageContent", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = new Float(359.13968F);
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setLatitude(float0);
      try { 
        inputVenueMessageContent1.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Longitude parameter can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.objects.inlinequery.inputmessagecontent.InputVenueMessageContent", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      String string0 = inputVenueMessageContent0.getAddress();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      String string0 = inputVenueMessageContent0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      String string0 = inputVenueMessageContent0.toString();
      assertEquals("InputVenueMessageContent{latitude=null, longitude=null, title='null', address='null', foursquareId='null', foursquareType='null'}", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      String string0 = inputVenueMessageContent0.getFoursquareType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setFoursquareId("");
      String string0 = inputVenueMessageContent1.getFoursquareId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = inputVenueMessageContent0.getLatitude();
      assertNull(float0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = inputVenueMessageContent0.getLongitude();
      assertNull(float0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      String string0 = inputVenueMessageContent0.getFoursquareId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      Float float0 = new Float(0.0);
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setLatitude(float0);
      Float float1 = inputVenueMessageContent1.getLatitude();
      assertEquals(0.0F, (float)float1, 0.01F);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      InputVenueMessageContent inputVenueMessageContent0 = new InputVenueMessageContent();
      InputVenueMessageContent inputVenueMessageContent1 = inputVenueMessageContent0.setAddress("p");
      Float float0 = new Float(0.0);
      InputVenueMessageContent inputVenueMessageContent2 = inputVenueMessageContent1.setLongitude(float0);
      InputVenueMessageContent inputVenueMessageContent3 = inputVenueMessageContent0.setTitle("p");
      InputVenueMessageContent inputVenueMessageContent4 = inputVenueMessageContent2.setLatitude(float0);
      inputVenueMessageContent4.validate();
      assertSame(inputVenueMessageContent4, inputVenueMessageContent3);
  }
}
