/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:46:57 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.Contact;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Contact_ESTest extends Contact_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Contact contact0 = new Contact();
      String string0 = contact0.getLastName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Contact contact0 = new Contact();
      String string0 = contact0.getPhoneNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Contact contact0 = new Contact();
      String string0 = contact0.getVCard();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Contact contact0 = new Contact();
      String string0 = contact0.getFirstName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Contact contact0 = new Contact();
      Integer integer0 = contact0.getUserID();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Contact contact0 = new Contact();
      String string0 = contact0.toString();
      assertEquals("Contact{phoneNumber='null', firstName='null', lastName='null', userID=null, vCard=null}", string0);
  }
}
