/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:41:42 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.security.InvalidParameterException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.File;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class File_ESTest extends File_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        File.getFileUrl((String) null, (String) null);
        fail("Expecting exception: InvalidParameterException");
      
      } catch(InvalidParameterException e) {
         //
         // Bot token can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.objects.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = File.getFileUrl(", fileSize=", ", fileSize=");
      assertEquals("https://api.telegram.org/file/bot, fileSize=/, fileSize=", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        File.getFileUrl("", "");
        fail("Expecting exception: InvalidParameterException");
      
      } catch(InvalidParameterException e) {
         //
         // Bot token can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.objects.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      File file0 = new File();
      // Undeclared exception!
      try { 
        file0.getFileUrl((String) null);
        fail("Expecting exception: InvalidParameterException");
      
      } catch(InvalidParameterException e) {
         //
         // Bot token can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.objects.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      File file0 = new File();
      String string0 = file0.toString();
      assertEquals("File{fileId='null', fileSize=null, filePath='null'}", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      File file0 = new File();
      String string0 = file0.getFileId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      File file0 = new File();
      String string0 = file0.getFileUrl(", fileSize=");
      assertEquals("https://api.telegram.org/file/bot, fileSize=/null", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      File file0 = new File();
      Integer integer0 = file0.getFileSize();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      File file0 = new File();
      String string0 = file0.getFilePath();
      assertNull(string0);
  }
}
