/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Oct 26 12:48:50 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Message_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.telegram.telegrambots.meta.api.objects.Message"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "/home/felipe/eclipse-workspace/TelegramBots/telegrambots-meta"); 
    java.lang.System.setProperty("user.home", "/home/felipe"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "felipe"); 
    java.lang.System.setProperty("user.timezone", "America/Recife"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Message_ESTest_scaffolding.class.getClassLoader() ,
      "com.fasterxml.jackson.annotation.JsonProperty",
      "org.telegram.telegrambots.meta.api.objects.payments.SuccessfulPayment",
      "org.telegram.telegrambots.meta.api.objects.stickers.Sticker",
      "org.telegram.telegrambots.meta.api.objects.Message",
      "org.telegram.telegrambots.meta.api.objects.MessageEntity",
      "org.telegram.telegrambots.meta.api.objects.payments.OrderInfo",
      "org.telegram.telegrambots.meta.api.objects.passport.EncryptedCredentials",
      "org.telegram.telegrambots.meta.api.objects.Chat",
      "com.fasterxml.jackson.annotation.JacksonAnnotation",
      "com.fasterxml.jackson.annotation.JsonInclude$Include",
      "org.telegram.telegrambots.meta.api.objects.Audio",
      "org.telegram.telegrambots.meta.api.interfaces.BotApiObject",
      "org.telegram.telegrambots.meta.api.objects.Voice",
      "org.telegram.telegrambots.meta.api.objects.Venue",
      "com.fasterxml.jackson.annotation.JsonProperty$Access",
      "org.telegram.telegrambots.meta.api.objects.User",
      "org.telegram.telegrambots.meta.api.objects.Video",
      "org.telegram.telegrambots.meta.api.objects.payments.Invoice",
      "org.telegram.telegrambots.meta.api.objects.passport.PassportData",
      "org.telegram.telegrambots.meta.api.objects.ChatPhoto",
      "org.telegram.telegrambots.meta.api.objects.games.Game",
      "org.telegram.telegrambots.meta.api.objects.VideoNote",
      "org.telegram.telegrambots.meta.api.objects.PhotoSize",
      "org.telegram.telegrambots.meta.api.objects.Contact",
      "org.telegram.telegrambots.meta.api.objects.Document",
      "org.telegram.telegrambots.meta.api.objects.Location",
      "com.fasterxml.jackson.annotation.JsonInclude",
      "org.telegram.telegrambots.meta.api.objects.games.Animation",
      "com.fasterxml.jackson.annotation.JsonIgnoreProperties",
      "org.telegram.telegrambots.meta.api.objects.payments.ShippingAddress"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Message_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.telegram.telegrambots.meta.api.objects.Message",
      "com.fasterxml.jackson.annotation.JsonProperty$Access",
      "org.telegram.telegrambots.meta.api.objects.User"
    );
  }
}
