/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:45:22 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.PhotoSize;
import org.telegram.telegrambots.meta.api.objects.VideoNote;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VideoNote_ESTest extends VideoNote_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VideoNote videoNote0 = new VideoNote();
      PhotoSize photoSize0 = videoNote0.getThumb();
      assertNull(photoSize0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      VideoNote videoNote0 = new VideoNote();
      Integer integer0 = videoNote0.getLength();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      VideoNote videoNote0 = new VideoNote();
      String string0 = videoNote0.toString();
      assertEquals("VideoNote{fileId='null', length=null, duration=null, thumb=null, fileSize=null}", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      VideoNote videoNote0 = new VideoNote();
      Integer integer0 = videoNote0.getFileSize();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      VideoNote videoNote0 = new VideoNote();
      String string0 = videoNote0.getFileId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      VideoNote videoNote0 = new VideoNote();
      Integer integer0 = videoNote0.getDuration();
      assertNull(integer0);
  }
}
