/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:47:52 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.PhotoSize;
import org.telegram.telegrambots.meta.api.objects.Video;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Video_ESTest extends Video_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Video video0 = new Video();
      Integer integer0 = video0.getFileSize();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Video video0 = new Video();
      PhotoSize photoSize0 = video0.getThumb();
      assertNull(photoSize0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Video video0 = new Video();
      Integer integer0 = video0.getDuration();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Video video0 = new Video();
      Integer integer0 = video0.getHeight();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Video video0 = new Video();
      String string0 = video0.getFileId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Video video0 = new Video();
      String string0 = video0.getMimeType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Video video0 = new Video();
      Integer integer0 = video0.getWidth();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Video video0 = new Video();
      String string0 = video0.toString();
      assertEquals("Video{fileId='null', width=null, height=null, duration=null, thumb=null, mimeType='null', fileSize=null}", string0);
  }
}
