/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:48:13 GMT 2018
 */

package org.telegram.telegrambots.meta.api.methods.updates;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.methods.updates.AllowedUpdates;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AllowedUpdates_ESTest extends AllowedUpdates_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AllowedUpdates allowedUpdates0 = new AllowedUpdates();
  }
}
