/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:42:06 GMT 2018
 */

package org.telegram.telegrambots.meta.api.methods.updates;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.methods.updates.GetWebhookInfo;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GetWebhookInfo_ESTest extends GetWebhookInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GetWebhookInfo getWebhookInfo0 = new GetWebhookInfo();
      // Undeclared exception!
      try { 
        getWebhookInfo0.deserializeResponse("{}\"g/O1e)Z:-\"iw_.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.updates.GetWebhookInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GetWebhookInfo getWebhookInfo0 = new GetWebhookInfo();
      getWebhookInfo0.validate();
      assertEquals("getwebhookinfo", getWebhookInfo0.getMethod());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GetWebhookInfo getWebhookInfo0 = new GetWebhookInfo();
      String string0 = getWebhookInfo0.toString();
      assertEquals("GetWebhookInfo{}", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GetWebhookInfo getWebhookInfo0 = new GetWebhookInfo();
      String string0 = getWebhookInfo0.getMethod();
      assertEquals("getwebhookinfo", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GetWebhookInfo getWebhookInfo0 = new GetWebhookInfo();
      try { 
        getWebhookInfo0.deserializeResponse("kgS");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Unable to deserialize response
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.updates.GetWebhookInfo", e);
      }
  }
}
