/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:44:36 GMT 2018
 */

package org.telegram.telegrambots.meta.api.methods.updates;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.methods.updates.SetWebhook;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SetWebhook_ESTest extends SetWebhook_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      setWebhook0.setUrl((String) null);
      String string0 = setWebhook0.getUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      setWebhook0.setUrl("I");
      String string0 = setWebhook0.getUrl();
      assertEquals("I", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      Integer integer0 = new Integer(0);
      SetWebhook setWebhook1 = setWebhook0.setMaxConnections(integer0);
      Integer integer1 = setWebhook1.getMaxConnections();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      Integer integer0 = new Integer(593);
      SetWebhook setWebhook1 = setWebhook0.setMaxConnections(integer0);
      Integer integer1 = setWebhook1.getMaxConnections();
      assertEquals(593, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      Integer integer0 = new Integer((-616));
      SetWebhook setWebhook1 = setWebhook0.setMaxConnections(integer0);
      Integer integer1 = setWebhook1.getMaxConnections();
      assertEquals((-616), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      SetWebhook setWebhook1 = setWebhook0.setCertificateFile("");
      String string0 = setWebhook1.getCertificateFile();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      String string0 = setWebhook0.getCertificateFile();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      String string0 = setWebhook0.toString();
      assertEquals("SetWebhook{url='', certificateFile='null', maxConnections=null, allowedUpdates=null}", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      String string0 = setWebhook0.getUrl();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      SetWebhook setWebhook1 = setWebhook0.setAllowedUpdates((List<String>) null);
      assertNull(setWebhook1.getCertificateFile());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      setWebhook0.setCertificateFile("certificate");
      String string0 = setWebhook0.getCertificateFile();
      assertEquals("certificate", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      List<String> list0 = setWebhook0.getAllowedUpdates();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SetWebhook setWebhook0 = new SetWebhook();
      Integer integer0 = setWebhook0.getMaxConnections();
      assertNull(integer0);
  }
}
