/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:05:12 GMT 2018
 */

package org.telegram.telegrambots.meta.api.methods.send;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.methods.send.SendMediaGroup;
import org.telegram.telegrambots.meta.api.objects.media.InputMedia;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SendMediaGroup_ESTest extends SendMediaGroup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      Integer integer0 = new Integer(0);
      sendMediaGroup0.setReplyToMessageId(integer0);
      Integer integer1 = sendMediaGroup0.getReplyToMessageId();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      Integer integer0 = new Integer(16);
      sendMediaGroup0.setReplyToMessageId(integer0);
      Integer integer1 = sendMediaGroup0.getReplyToMessageId();
      assertEquals(16, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      Integer integer0 = new Integer((-604));
      SendMediaGroup sendMediaGroup1 = sendMediaGroup0.setReplyToMessageId(integer0);
      Integer integer1 = sendMediaGroup1.getReplyToMessageId();
      assertEquals((-604), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      sendMediaGroup0.setChatId("sendMediaGroup");
      String string0 = sendMediaGroup0.getChatId();
      assertEquals("sendMediaGroup", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      SendMediaGroup sendMediaGroup1 = sendMediaGroup0.setChatId("");
      String string0 = sendMediaGroup1.getChatId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      // Undeclared exception!
      try { 
        sendMediaGroup0.setChatId((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      // Undeclared exception!
      try { 
        sendMediaGroup0.setChatId((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      // Undeclared exception!
      try { 
        sendMediaGroup0.deserializeResponse((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.core.JsonFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      try { 
        sendMediaGroup0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // ChatId parameter can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.send.SendMediaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      sendMediaGroup0.setChatId("chat_id");
      try { 
        sendMediaGroup0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Media parameter can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.send.SendMediaGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      SendMediaGroup sendMediaGroup1 = sendMediaGroup0.enableNotification();
      Boolean boolean0 = sendMediaGroup1.getDisableNotification();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      Integer integer0 = sendMediaGroup0.getReplyToMessageId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      Boolean boolean0 = sendMediaGroup0.getDisableNotification();
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = null;
      try {
        sendMediaGroup0 = new SendMediaGroup("", (List<InputMedia>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Long long0 = new Long((-4227L));
      SendMediaGroup sendMediaGroup0 = null;
      try {
        sendMediaGroup0 = new SendMediaGroup(long0, (List<InputMedia>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      String string0 = sendMediaGroup0.toString();
      assertEquals("SendMediaGroup{chatId='null', media=null, replyToMessageId=null, disableNotification=null}", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      String string0 = sendMediaGroup0.getChatId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      SendMediaGroup sendMediaGroup1 = sendMediaGroup0.disableNotification();
      Boolean boolean0 = sendMediaGroup1.getDisableNotification();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      Long long0 = new Long(0L);
      SendMediaGroup sendMediaGroup1 = sendMediaGroup0.setChatId(long0);
      assertSame(sendMediaGroup1, sendMediaGroup0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SendMediaGroup sendMediaGroup0 = new SendMediaGroup();
      try { 
        sendMediaGroup0.deserializeResponse("disable_notification");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Unable to deserialize response
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.send.SendMediaGroup", e);
      }
  }
}
