/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:48:56 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects.inlinequery;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.Location;
import org.telegram.telegrambots.meta.api.objects.User;
import org.telegram.telegrambots.meta.api.objects.inlinequery.ChosenInlineQuery;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ChosenInlineQuery_ESTest extends ChosenInlineQuery_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChosenInlineQuery chosenInlineQuery0 = new ChosenInlineQuery();
      String string0 = chosenInlineQuery0.getResultId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ChosenInlineQuery chosenInlineQuery0 = new ChosenInlineQuery();
      String string0 = chosenInlineQuery0.getQuery();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ChosenInlineQuery chosenInlineQuery0 = new ChosenInlineQuery();
      String string0 = chosenInlineQuery0.toString();
      assertEquals("ChosenInlineQuery{resultId='null', from=null, location=null, inlineMessageId=null, query='null'}", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ChosenInlineQuery chosenInlineQuery0 = new ChosenInlineQuery();
      Location location0 = chosenInlineQuery0.getLocation();
      assertNull(location0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ChosenInlineQuery chosenInlineQuery0 = new ChosenInlineQuery();
      String string0 = chosenInlineQuery0.getInlineMessageId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ChosenInlineQuery chosenInlineQuery0 = new ChosenInlineQuery();
      User user0 = chosenInlineQuery0.getFrom();
      assertNull(user0);
  }
}
