/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:37:00 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects.inlinequery;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.Location;
import org.telegram.telegrambots.meta.api.objects.User;
import org.telegram.telegrambots.meta.api.objects.inlinequery.InlineQuery;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InlineQuery_ESTest extends InlineQuery_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InlineQuery inlineQuery0 = new InlineQuery();
      boolean boolean0 = inlineQuery0.hasLocation();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InlineQuery inlineQuery0 = new InlineQuery();
      boolean boolean0 = inlineQuery0.hasQuery();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      InlineQuery inlineQuery0 = new InlineQuery();
      Location location0 = inlineQuery0.getLocation();
      assertNull(location0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      InlineQuery inlineQuery0 = new InlineQuery();
      String string0 = inlineQuery0.getQuery();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      InlineQuery inlineQuery0 = new InlineQuery();
      String string0 = inlineQuery0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      InlineQuery inlineQuery0 = new InlineQuery();
      String string0 = inlineQuery0.toString();
      assertEquals("InlineQuery{id='null', from=null, location=null, query='null', offset='null'}", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      InlineQuery inlineQuery0 = new InlineQuery();
      String string0 = inlineQuery0.getOffset();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      InlineQuery inlineQuery0 = new InlineQuery();
      User user0 = inlineQuery0.getFrom();
      assertNull(user0);
  }
}
