/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:42:19 GMT 2018
 */

package org.telegram.telegrambots.meta.api.methods.groupadministration;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.methods.groupadministration.DeleteChatPhoto;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DeleteChatPhoto_ESTest extends DeleteChatPhoto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto();
      String string0 = deleteChatPhoto0.getChatId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto("");
      String string0 = deleteChatPhoto0.getChatId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto("org.telegram.telegrambots.meta.api.methods.groupadministration.DeleteChatPhoto");
      // Undeclared exception!
      try { 
        deleteChatPhoto0.setChatId((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Long long0 = new Long((-285L));
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto(long0);
      // Undeclared exception!
      try { 
        deleteChatPhoto0.deserializeResponse((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.core.JsonFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DeleteChatPhoto deleteChatPhoto0 = null;
      try {
        deleteChatPhoto0 = new DeleteChatPhoto((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DeleteChatPhoto deleteChatPhoto0 = null;
      try {
        deleteChatPhoto0 = new DeleteChatPhoto((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto("$}|f]fl! VM");
      deleteChatPhoto0.validate();
      assertEquals("$}|f]fl! VM", deleteChatPhoto0.getChatId());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Long long0 = new Long(0L);
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto(long0);
      try { 
        deleteChatPhoto0.deserializeResponse("deleteChatPhoto");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Unable to deserialize response
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.groupadministration.DeleteChatPhoto", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto();
      try { 
        deleteChatPhoto0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // ChatId can't be null
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.groupadministration.DeleteChatPhoto", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Long long0 = new Long(0L);
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto(long0);
      String string0 = deleteChatPhoto0.getMethod();
      assertEquals("deleteChatPhoto", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto("org.telegram.telegrambots.meta.api.methods.groupadministration.DeleteChatPhoto");
      Long long0 = new Long(942L);
      DeleteChatPhoto deleteChatPhoto1 = deleteChatPhoto0.setChatId(long0);
      assertEquals("942", deleteChatPhoto1.getChatId());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto("org.telegram.telegrambots.meta.api.methods.groupadministration.DeleteChatPhoto");
      String string0 = deleteChatPhoto0.toString();
      assertEquals("DeleteChatPhoto{chatId='org.telegram.telegrambots.meta.api.methods.groupadministration.DeleteChatPhoto'}", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto("$}|f]fl! VM");
      String string0 = deleteChatPhoto0.getChatId();
      assertEquals("$}|f]fl! VM", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Long long0 = new Long(0L);
      DeleteChatPhoto deleteChatPhoto0 = new DeleteChatPhoto(long0);
      DeleteChatPhoto deleteChatPhoto1 = deleteChatPhoto0.setChatId("deleteChatPhoto");
      assertSame(deleteChatPhoto1, deleteChatPhoto0);
  }
}
