/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:36:21 GMT 2018
 */

package org.telegram.telegrambots.meta.api.methods.groupadministration;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.methods.groupadministration.GetChat;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GetChat_ESTest extends GetChat_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GetChat getChat0 = new GetChat();
      Long long0 = new Long(1L);
      GetChat getChat1 = getChat0.setChatId(long0);
      assertEquals("1", getChat1.getChatId());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GetChat getChat0 = new GetChat();
      String string0 = getChat0.getChatId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GetChat getChat0 = new GetChat("");
      String string0 = getChat0.getChatId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GetChat getChat0 = new GetChat();
      // Undeclared exception!
      try { 
        getChat0.deserializeResponse((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.core.JsonFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GetChat getChat0 = null;
      try {
        getChat0 = new GetChat((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GetChat getChat0 = null;
      try {
        getChat0 = new GetChat((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Long long0 = new Long(0L);
      GetChat getChat0 = new GetChat(long0);
      getChat0.validate();
      assertEquals("getChat", getChat0.getMethod());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GetChat getChat0 = new GetChat();
      try { 
        getChat0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // ChatId can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.groupadministration.GetChat", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Long long0 = new Long(0L);
      GetChat getChat0 = new GetChat(long0);
      try { 
        getChat0.deserializeResponse("getChat");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Unable to deserialize response
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.groupadministration.GetChat", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Long long0 = new Long(0L);
      GetChat getChat0 = new GetChat(long0);
      String string0 = getChat0.getChatId();
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GetChat getChat0 = new GetChat();
      // Undeclared exception!
      try { 
        getChat0.setChatId((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GetChat getChat0 = new GetChat();
      String string0 = getChat0.getMethod();
      assertEquals("getChat", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GetChat getChat0 = new GetChat("File to parsetype  '");
      getChat0.setChatId("");
      try { 
        getChat0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // ChatId can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.groupadministration.GetChat", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GetChat getChat0 = new GetChat("com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer");
      String string0 = getChat0.toString();
      assertEquals("GetChat{chatId='com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer'}", string0);
  }
}
