/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:33:09 GMT 2018
 */

package org.telegram.telegrambots.meta.api.methods.groupadministration;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.methods.groupadministration.GetChatMember;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GetChatMember_ESTest extends GetChatMember_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      Integer integer0 = new Integer(1892);
      getChatMember0.setUserId(integer0);
      Integer integer1 = getChatMember0.getUserId();
      assertEquals(1892, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      Integer integer0 = Integer.valueOf(0);
      GetChatMember getChatMember1 = getChatMember0.setUserId(integer0);
      Integer integer1 = getChatMember1.getUserId();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      Integer integer0 = Integer.getInteger("getChatMember", (-4654));
      GetChatMember getChatMember1 = getChatMember0.setUserId(integer0);
      Integer integer1 = getChatMember1.getUserId();
      assertEquals((-4654), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      Long long0 = new Long((-898L));
      getChatMember0.setChatId(long0);
      String string0 = getChatMember0.getChatId();
      assertEquals("-898", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      getChatMember0.setChatId("");
      String string0 = getChatMember0.getChatId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      // Undeclared exception!
      try { 
        getChatMember0.setChatId((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      // Undeclared exception!
      try { 
        getChatMember0.deserializeResponse("null array");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.groupadministration.GetChatMember", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      GetChatMember getChatMember1 = getChatMember0.setChatId("");
      try { 
        getChatMember1.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // ChatId can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.groupadministration.GetChatMember", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      try { 
        getChatMember0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // ChatId can't be empty
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.groupadministration.GetChatMember", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      try { 
        getChatMember0.deserializeResponse("Error getting chat member");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Unable to deserialize response
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.groupadministration.GetChatMember", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      getChatMember0.setChatId("getChatMember");
      try { 
        getChatMember0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // UserId can't be null
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.groupadministration.GetChatMember", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      Long long0 = new Long(0L);
      GetChatMember getChatMember1 = getChatMember0.setChatId(long0);
      Integer integer0 = new Integer(1);
      GetChatMember getChatMember2 = getChatMember1.setUserId(integer0);
      getChatMember2.validate();
      assertEquals(1, (int)getChatMember2.getUserId());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      String string0 = getChatMember0.getChatId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      String string0 = getChatMember0.getMethod();
      assertEquals("getChatMember", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      String string0 = getChatMember0.toString();
      assertEquals("GetChatMember{chatId='null', userId='null'}", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GetChatMember getChatMember0 = new GetChatMember();
      Integer integer0 = getChatMember0.getUserId();
      assertNull(integer0);
  }
}
