/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 12:47:17 GMT 2018
 */

package org.telegram.telegrambots.meta;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.TelegramBotsApi;
import org.telegram.telegrambots.meta.generics.LongPollingBot;
import org.telegram.telegrambots.meta.generics.WebhookBot;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TelegramBotsApi_ESTest extends TelegramBotsApi_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = new TelegramBotsApi();
      LongPollingBot longPollingBot0 = mock(LongPollingBot.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        telegramBotsApi0.registerBot(longPollingBot0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Guice configuration errors:
         // 
         // 1) No implementation for org.telegram.telegrambots.meta.generics.BotSession was bound.
         //   while locating org.telegram.telegrambots.meta.generics.BotSession
         // 
         // 1 error
         //
         verifyException("com.google.inject.internal.InjectorImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = new TelegramBotsApi();
      WebhookBot webhookBot0 = mock(WebhookBot.class, new ViolatedAssumptionAnswer());
      telegramBotsApi0.registerBot(webhookBot0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("'", "'", "'", "{0}callback/", "{0}callback/");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Guice configuration errors:
         // 
         // 1) No implementation for org.telegram.telegrambots.meta.generics.Webhook was bound.
         //   while locating org.telegram.telegrambots.meta.generics.Webhook
         // 
         // 1 error
         //
         verifyException("com.google.inject.internal.InjectorImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("7sHM4X6;l_5", "7sHM4X6;l_5", "7sHM4X6;l_5", "7sHM4X6;l_5", (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter pathToCertificate can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("JoN|%n_Re#kEJZJk!I", "", "JoN|%n_Re#kEJZJk!I", "JoN|%n_Re#kEJZJk!I", "");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter keyStorePassword can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("cl|t2Yly9 ig2`>5/Tw/", (String) null, "cl|t2Yly9 ig2`>5/Tw/", "cl|t2Yly9 ig2`>5/Tw/", (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter keyStorePassword can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("", "WUWjhYN& Rcwn'.", "WUWjhYN& Rcwn'.", "B1lcNE?pKc9m>LZww]", "APIEXCEPTION");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter keyStore can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi((String) null, (String) null, "EdU2'", "EdU2'", (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter keyStore can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("", "", "u:7^>", "", "");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter internalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("[n_2q}'b", "[n_2q}'b", "[n_2q}'b", (String) null, "[n_2q}'b");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter internalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi(" EG$btEM|f", "Pev)", " EG$btEM|f", "ylI", "");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter pathToCertificate can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("", "", "", (String) null, (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter externalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("L8qY PfG;6", "O*>r4r<Rz>k_Ym", (String) null, (String) null, (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter externalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("s##\"?L[k&", "", "s##\"?L[k&", "s##\"?L[k&");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter keyStorePassword can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("at26{qmI9hM$o", (String) null, "at26{qmI9hM$o", "Hc^KwzRJbZx1");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter keyStorePassword can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("/", "/", "/", "/");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Guice configuration errors:
         // 
         // 1) No implementation for org.telegram.telegrambots.meta.generics.Webhook was bound.
         //   while locating org.telegram.telegrambots.meta.generics.Webhook
         // 
         // 1 error
         //
         verifyException("com.google.inject.internal.InjectorImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi((String) null, (String) null, "]jwGgI!UE!hDJ", "]jwGgI!UE!hDJ");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter keyStore can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("y^pi*4C8NOBt/o0v'GD", "y^pi*4C8NOBt/o0v'GD", "y^pi*4C8NOBt/o0v'GD", "");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter internalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi(": ", ": ", ": ", (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter internalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("", "", "hiFd86Ocx", "hiFd86Ocx");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter keyStore can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("", "", "", "");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter externalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi((String) null, (String) null, (String) null, (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter externalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("org.telegram.telegrambots.meta.TelegramBotsApi", "");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter internalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("?enOhO", "?enOhO");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Guice configuration errors:
         // 
         // 1) No implementation for org.telegram.telegrambots.meta.generics.Webhook was bound.
         //   while locating org.telegram.telegrambots.meta.generics.Webhook
         // 
         // 1 error
         //
         verifyException("com.google.inject.internal.InjectorImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("2p)Jo~T+gN:1w", (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter internalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi("", "");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter externalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = null;
      try {
        telegramBotsApi0 = new TelegramBotsApi((String) null, (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Parameter externalUrl can not be null or empty
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TelegramBotsApi telegramBotsApi0 = new TelegramBotsApi();
      // Undeclared exception!
      try { 
        telegramBotsApi0.registerBot((LongPollingBot) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.meta.TelegramBotsApi", e);
      }
  }
}
