/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:35:16 GMT 2018
 */

package org.telegram.telegrambots.meta.api.methods.stickers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.methods.stickers.GetStickerSet;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GetStickerSet_ESTest extends GetStickerSet_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GetStickerSet getStickerSet0 = new GetStickerSet();
      String string0 = getStickerSet0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GetStickerSet getStickerSet0 = new GetStickerSet("aLFGj8");
      getStickerSet0.setName("");
      String string0 = getStickerSet0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GetStickerSet getStickerSet0 = new GetStickerSet("null");
      // Undeclared exception!
      try { 
        getStickerSet0.deserializeResponse("null");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.stickers.GetStickerSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GetStickerSet getStickerSet0 = null;
      try {
        getStickerSet0 = new GetStickerSet((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GetStickerSet getStickerSet0 = new GetStickerSet();
      GetStickerSet getStickerSet1 = getStickerSet0.setName("");
      try { 
        getStickerSet1.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Name can't be null
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.stickers.GetStickerSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GetStickerSet getStickerSet0 = new GetStickerSet("v");
      getStickerSet0.validate();
      assertEquals("v", getStickerSet0.getName());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GetStickerSet getStickerSet0 = new GetStickerSet();
      try { 
        getStickerSet0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Name can't be null
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.stickers.GetStickerSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GetStickerSet getStickerSet0 = new GetStickerSet("aLFGj8");
      try { 
        getStickerSet0.deserializeResponse("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Unable to deserialize response
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.stickers.GetStickerSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GetStickerSet getStickerSet0 = new GetStickerSet();
      String string0 = getStickerSet0.toString();
      assertEquals("GetStickerSet{name='null'}", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GetStickerSet getStickerSet0 = new GetStickerSet("aLFGj8");
      String string0 = getStickerSet0.getName();
      assertEquals("aLFGj8", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GetStickerSet getStickerSet0 = new GetStickerSet("v");
      String string0 = getStickerSet0.getMethod();
      assertEquals("getStickerSet", string0);
  }
}
