/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:21:28 GMT 2018
 */

package org.telegram.telegrambots.meta.api.methods.stickers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.methods.stickers.SetStickerPositionInSet;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SetStickerPositionInSet_ESTest extends SetStickerPositionInSet_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = new Integer((-571));
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet("Error setting sticker position in set", integer0);
      setStickerPositionInSet0.validate();
      assertEquals((-571), (int)setStickerPositionInSet0.getPosition());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet();
      String string0 = setStickerPositionInSet0.getSticker();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = Integer.valueOf(39);
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet("", integer0);
      String string0 = setStickerPositionInSet0.getSticker();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet();
      Integer integer0 = setStickerPositionInSet0.getPosition();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Integer integer0 = new Integer(0);
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet("uv J?)d&1G R", integer0);
      Integer integer1 = setStickerPositionInSet0.getPosition();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet();
      Integer integer0 = new Integer(125);
      SetStickerPositionInSet setStickerPositionInSet1 = setStickerPositionInSet0.setPosition(integer0);
      Integer integer1 = setStickerPositionInSet1.getPosition();
      assertEquals(125, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet();
      // Undeclared exception!
      try { 
        setStickerPositionInSet0.deserializeResponse("{}la3#lI6d");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.stickers.SetStickerPositionInSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SetStickerPositionInSet setStickerPositionInSet0 = null;
      try {
        setStickerPositionInSet0 = new SetStickerPositionInSet("not one of values excepted for Enum class: %s", (Integer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Integer integer0 = new Integer(2288);
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet("WRITE_FMBERS_C_STRGS", integer0);
      try { 
        setStickerPositionInSet0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // position can't be null
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.stickers.SetStickerPositionInSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet();
      SetStickerPositionInSet setStickerPositionInSet1 = setStickerPositionInSet0.setSticker("getStickerSet");
      try { 
        setStickerPositionInSet1.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // position can't be null
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.stickers.SetStickerPositionInSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer(0);
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet("v", integer0);
      setStickerPositionInSet0.validate();
      assertEquals("v", setStickerPositionInSet0.getSticker());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet();
      try { 
        setStickerPositionInSet0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // sticker can't be null
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.stickers.SetStickerPositionInSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet("", integer0);
      try { 
        setStickerPositionInSet0.deserializeResponse("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Unable to deserialize response
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.stickers.SetStickerPositionInSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet("", integer0);
      Integer integer1 = setStickerPositionInSet0.getPosition();
      assertEquals((-1), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet();
      setStickerPositionInSet0.setSticker("");
      try { 
        setStickerPositionInSet0.validate();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // sticker can't be null
         //
         verifyException("org.telegram.telegrambots.meta.api.methods.stickers.SetStickerPositionInSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet();
      String string0 = setStickerPositionInSet0.getMethod();
      assertEquals("getStickerSet", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Integer integer0 = new Integer(2288);
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet("WRITE_FMBERS_C_STRGS", integer0);
      String string0 = setStickerPositionInSet0.getSticker();
      assertEquals("WRITE_FMBERS_C_STRGS", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Integer integer0 = new Integer(0);
      SetStickerPositionInSet setStickerPositionInSet0 = new SetStickerPositionInSet("v", integer0);
      String string0 = setStickerPositionInSet0.toString();
      assertEquals("SetStickerPositionInSet{sticker='v', position=0}", string0);
  }
}
