/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:43:52 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects.games;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.games.CallbackGame;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CallbackGame_ESTest extends CallbackGame_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CallbackGame callbackGame0 = new CallbackGame();
      String string0 = callbackGame0.toString();
      assertEquals("CallbackGame{}", string0);
  }
}
