/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 13:36:25 GMT 2018
 */

package org.telegram.telegrambots.meta.api.objects.games;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.meta.api.objects.MessageEntity;
import org.telegram.telegrambots.meta.api.objects.PhotoSize;
import org.telegram.telegrambots.meta.api.objects.games.Animation;
import org.telegram.telegrambots.meta.api.objects.games.Game;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Game_ESTest extends Game_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Game game0 = new Game();
      boolean boolean0 = game0.hasEntities();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Game game0 = new Game();
      List<MessageEntity> list0 = game0.getEntities();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Game game0 = new Game();
      List<PhotoSize> list0 = game0.getPhoto();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Game game0 = new Game();
      String string0 = game0.toString();
      assertEquals("Game{title='null', description='null', photo=null, animation=null}", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Game game0 = new Game();
      Animation animation0 = game0.getAnimation();
      assertNull(animation0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Game game0 = new Game();
      String string0 = game0.getText();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Game game0 = new Game();
      String string0 = game0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Game game0 = new Game();
      String string0 = game0.getDescription();
      assertNull(string0);
  }
}
